version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

    commands:
      - echo installing

  pre_build:
    commands:
      - echo build


  build:
    commands:
      - echo deploy

  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - template.yaml
  name: upbCodepipeline
  
