version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

    commands:
      - ./deploy.sh -i

  pre_build:
    commands:
      - echo build


  build:
    commands:
      - ./deploy.sh -b

  post_build:
    commands:
      - echo post_builds

artifacts:
  files:
    - template.yaml
  name: upbCodepipeline
  
