AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Project: 
    Type: String

Description: my template
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "bucket-12-bucket12"